### ISSUE TITLE
Deprecation notice on PrivacyPolicy::register_h5pxapikatchu_eraser()

### ISSUE THREAD

**Issue by figureone** [otacke/h5pxapikatchu#16]
Aloha, we noticed the following warning when interacting with the Personal Data Erasure tool in WordPress. Probably just needs to be updated for the latest API:
https://developer.wordpress.org/plugins/privacy/adding-the-personal-data-eraser-to-your-plugin/

Warning:
`Deprecated: Non-static method H5PXAPIKATCHU\PrivacyPolicy::register_h5pxapikatchu_eraser() should not be called statically in /var/www/html/wp-includes/class-wp-hook.php on line 287`

Example:
![Screen Shot 2020-06-01 at 3 19 01 PM](https://user-images.githubusercontent.com/125274/83469399-4a8c4380-a41b-11ea-81f7-8c1176c8335f.png)

**Comment by otacke** [comment]
@figureone Thanks for the hint. I wasn't aware of these changes. I'll have a look when I find some time.

**Comment by otacke** [comment]
@figureone Fixed. Will be part of next update.
