### ISSUE TITLE
Tracking choices in Branching Scenario media type

### ISSUE THREAD

**Issue by bphokie** [otacke/h5pxapikatchu#18]
This plug-in does not appear to track branching scenario choices. Is this a planned feature to be added?

Thank you for such a great plug-in. Love the raw data!

**Comment by otacke** [comment]
@bphokie The plugin doesn't limit tracking to anything unless you tell it to. Have you checked whether Branching Scenario emits xAPI statements?

**Comment by otacke** [comment]
@bphokie Have you found time to take a look meanwhile?

**Comment by bphokie** [comment]
Apologies, I have not had time to look until now. It appears that the only xAPI coverage is of progression and completion. I was hoping, at the very least, to be able to see which choice they make at each juncture of the branching scenario. Do you have any suggestions for this implementation?
Thank you for your attentiveness.

**Comment by otacke** [comment]
@bphokie Feel free to also check Branching Question for how it handles xAPI. It could either be (made) an xAPI activity of type "choice" or be amended to also trigger some "chosen" statement (http://xapi.vocab.pub/verbs). Might be a good idea to pre-qualify this with the H5P core team.

**Comment by bphokie** [comment]
I think being able to amend the 'answered' function with a chosen statement to simply record which choice was made would be best for our needs. I am not quite sure how to do this, do you have any documentation or resources you can recommend to achieve this task? Thank you.

**Comment by otacke** [comment]
@bphokie I took a look at Branching Question. It already comes with all the necessary xAPI features (see https://github.com/h5p/h5p-branching-question/blob/master/branchingQuestion.js#L248-L256). It just doesn't send them out actively. You'd just need to create the xAPIEvent the same way right before https://github.com/h5p/h5p-branching-question/blob/master/branchingQuestion.js#L138 and trigger that event, then any application that listens to H5P's xAPI statements can pick it up, too.
